extends RefCounted

const ENGLISH := "en"
const PERSIAN := "fa"

var current_language := ENGLISH

var translations := {
	ENGLISH: {
		"app.title": "QuestBoard",
		"home.empty_message": "No story yet. Create your first story to begin your journey.",
		"home.create_custom_story": "Create Custom Story",
		"home.start_from_template": "Start From Template",
		"home.settings": "Settings",
		"story.title_placeholder": "Story title",
		"story.description_placeholder": "Story description",
		"story.goal": "Goal",
		"story.goal_placeholder": "Story goal",
		"story.create": "Create",
		"common.cancel": "Cancel",
		"common.back": "Back",
		"common.back_to_home": "Back to Home",
		"template.choose": "Choose a Story Template",
		"dashboard.current_paths": "Current paths",
		"dashboard.suggested_paths": "Suggested paths",
		"dashboard.no_paths": "No paths yet. Add your first path to shape this story.",
		"dashboard.add_path": "Add Path",
		"dashboard.add_sprint": "Add Sprint",
		"dashboard.add_quest": "Add Quest",
		"dashboard.add_path_before_sprint": "Add at least one path before creating a sprint.",
		"dashboard.sprints": "Sprints",
		"settings.title": "Settings",
		"settings.language": "App language",
		"settings.english": "English",
		"settings.persian": "Persian",
		"error.empty_story_title": "Please enter a story title.",
		"error.empty_path_name": "Please enter a path name.",
		"error.empty_sprint_title": "Please enter a sprint title.",
		"error.empty_quest_title": "Please enter a quest title.",
		"error.empty_objective_title": "Please enter an objective title.",
		"error.select_active_path": "Select at least one active path for this sprint.",
		"error.duplicate_path": "This path already exists.",
		"path.name_placeholder": "Path name",
		"path.icon_placeholder": "Icon text, optional",
		"path.create": "Create Path",
		"path.add_from_suggestions": "Add from suggested paths",
		"sprint.title_placeholder": "Sprint title",
		"sprint.start_date_placeholder": "Start date",
		"sprint.end_date_placeholder": "End date",
		"sprint.create_custom": "Create Custom Sprint",
		"sprint.start_from_template": "Start From Sprint Template",
		"sprint.templates": "Sprint Templates",
		"sprint.duration": "Duration",
		"sprint.days": "days",
		"sprint.duration_format": "%s %s",
		"sprint.suggested_name": "Suggested name",
		"sprint.create": "Create Sprint",
		"sprint.label": "Sprint",
		"sprint.select_active_paths": "Select Active Paths",
		"sprint.select_active_paths_hint": "Choose which paths belong to this sprint.",
		"sprint.save_active_paths": "Save Active Paths",
		"quest.add": "Add Quest",
		"quest.create": "Create Quest",
		"quest.quests": "Quests",
		"quest.no_quests": "No quests yet.",
		"quest.title_placeholder": "Quest title",
		"quest.description_placeholder": "Quest description",
		"quest.due_date_placeholder": "Due date",
		"quest.status_planned": "Planned",
		"quest.status_active": "Active",
		"quest.status_done": "Done",
		"objective.add": "Add Objective",
		"objective.save": "Save Objective",
		"objective.edit": "Edit",
		"objective.delete": "Delete",
		"objective.title_placeholder": "Objective title",
		"objective.no_objectives": "No objectives yet.",
		"progress.story": "Story Progress",
		"progress.quest": "Quest Progress",
		"sprint_template.start.title": "Start",
		"sprint_template.start.subtitle": "A short two-day sprint to begin without pressure.",
		"sprint_template.start.suggested_name": "Sprint 01 - Start",
		"sprint_template.rising.title": "Rising",
		"sprint_template.rising.subtitle": "A focused sprint for getting back on your feet.",
		"sprint_template.rising.suggested_name": "Sprint 01 - Rising",
		"sprint_template.day_zero.title": "Day Zero",
		"sprint_template.day_zero.subtitle": "A reset sprint for clearing the ground and choosing direction.",
		"sprint_template.day_zero.suggested_name": "Sprint 00 - Day Zero",
		"sprint_template.rhythm.title": "Build Rhythm",
		"sprint_template.rhythm.subtitle": "A three-day sprint for building a simple daily rhythm.",
		"sprint_template.rhythm.suggested_name": "Sprint 01 - Build Rhythm",
		"sprint_template.focus.title": "Focus Run",
		"sprint_template.focus.subtitle": "A focused three-day sprint for finishing a small meaningful outcome.",
		"sprint_template.focus.suggested_name": "Sprint 01 - Focus Run",
		"template.starting_over.title": "Starting Over",
		"template.starting_over.description": "Rebuild your life step by step after a difficult change.",
		"template.starting_over.goal": "Rebuild a steady daily rhythm.",
		"template.build_my_first_product.title": "Build My First Product",
		"template.build_my_first_product.description": "Turn an idea into a small usable product through focused sprints.",
		"template.build_my_first_product.goal": "Publish the first usable version.",
		"template.health_reset.title": "Health Reset",
		"template.health_reset.description": "Improve energy, fitness, sleep, and daily discipline.",
		"template.health_reset.goal": "Build a healthier daily routine.",
		"template.learning_sprint.title": "Learning Sprint",
		"template.learning_sprint.description": "Learn a new skill through daily practice and measurable progress.",
		"template.learning_sprint.goal": "Complete a small skill project.",
		"template.career_comeback.title": "Career Comeback",
		"template.career_comeback.description": "Improve your resume, apply for jobs, prepare for interviews, and rebuild professional momentum.",
		"template.career_comeback.goal": "Reach a clear next career opportunity.",
		"path.health_fitness": "Health & Fitness",
		"path.learning": "Learning",
		"path.income": "Income",
		"path.family": "Family",
		"path.creation": "Creation",
		"path.rest": "Rest",
		"path.product": "Product",
		"path.marketing": "Marketing",
		"path.nutrition": "Nutrition",
		"path.sleep": "Sleep",
		"path.mindset": "Mindset",
		"path.study": "Study",
		"path.practice": "Practice",
		"path.projects": "Projects",
		"path.review": "Review",
		"path.resume": "Resume",
		"path.applications": "Applications",
		"path.interview_practice": "Interview Practice"
	},
	PERSIAN: {
		"app.title": "کوئست‌بورد",
		"home.empty_message": "هنوز داستانی وجود ندارد. اولین داستان خود را بسازید و مسیرتان را آغاز کنید.",
		"home.create_custom_story": "ساخت داستان دلخواه",
		"home.start_from_template": "شروع با قالب آماده",
		"home.settings": "تنظیمات",
		"story.title_placeholder": "عنوان داستان",
		"story.description_placeholder": "توضیح داستان",
		"story.goal": "هدف",
		"story.goal_placeholder": "هدف داستان",
		"story.create": "ساخت",
		"common.cancel": "لغو",
		"common.back": "بازگشت",
		"common.back_to_home": "بازگشت به خانه",
		"template.choose": "یک قالب داستان انتخاب کنید",
		"dashboard.current_paths": "مسیرهای فعلی",
		"dashboard.suggested_paths": "مسیرهای پیشنهادی",
		"dashboard.no_paths": "هنوز مسیری ساخته نشده است. اولین مسیر را برای شکل دادن به این داستان اضافه کنید.",
		"dashboard.add_path": "افزودن مسیر",
		"dashboard.add_sprint": "افزودن اسپرینت",
		"dashboard.add_quest": "افزودن کوئست",
		"dashboard.add_path_before_sprint": "قبل از ساخت اسپرینت، حداقل یک مسیر اضافه کنید.",
		"dashboard.sprints": "اسپرینت‌ها",
		"settings.title": "تنظیمات",
		"settings.language": "زبان برنامه",
		"settings.english": "انگلیسی",
		"settings.persian": "فارسی",
		"error.empty_story_title": "لطفا عنوان داستان را وارد کنید.",
		"error.empty_path_name": "لطفا نام مسیر را وارد کنید.",
		"error.empty_sprint_title": "لطفا عنوان اسپرینت را وارد کنید.",
		"error.empty_quest_title": "لطفا عنوان کوئست را وارد کنید.",
		"error.empty_objective_title": "لطفا عنوان آبجکتیو را وارد کنید.",
		"error.select_active_path": "برای این اسپرینت حداقل یک مسیر فعال انتخاب کنید.",
		"error.duplicate_path": "این مسیر از قبل وجود دارد.",
		"path.name_placeholder": "نام مسیر",
		"path.icon_placeholder": "متن آیکون، اختیاری",
		"path.create": "ساخت مسیر",
		"path.add_from_suggestions": "افزودن از مسیرهای پیشنهادی",
		"sprint.title_placeholder": "عنوان اسپرینت",
		"sprint.start_date_placeholder": "تاریخ شروع",
		"sprint.end_date_placeholder": "تاریخ پایان",
		"sprint.create_custom": "ساخت اسپرینت دلخواه",
		"sprint.start_from_template": "شروع با قالب اسپرینت",
		"sprint.templates": "قالب‌های اسپرینت",
		"sprint.duration": "مدت",
		"sprint.days": "روز",
		"sprint.duration_format": "%s %s",
		"sprint.suggested_name": "نام پیشنهادی",
		"sprint.create": "ساخت اسپرینت",
		"sprint.label": "اسپرینت",
		"sprint.select_active_paths": "انتخاب مسیرهای فعال",
		"sprint.select_active_paths_hint": "انتخاب کنید کدام مسیرها داخل این اسپرینت هستند.",
		"sprint.save_active_paths": "ذخیره مسیرهای فعال",
		"quest.add": "افزودن کوئست",
		"quest.create": "ساخت کوئست",
		"quest.quests": "کوئست‌ها",
		"quest.no_quests": "هنوز کوئستی ساخته نشده است.",
		"quest.title_placeholder": "عنوان کوئست",
		"quest.description_placeholder": "توضیح کوئست",
		"quest.due_date_placeholder": "تاریخ انجام",
		"quest.status_planned": "برنامه‌ریزی‌شده",
		"quest.status_active": "فعال",
		"quest.status_done": "انجام‌شده",
		"objective.add": "افزودن آبجکتیو",
		"objective.save": "ذخیره آبجکتیو",
		"objective.edit": "ویرایش",
		"objective.delete": "حذف",
		"objective.title_placeholder": "عنوان آبجکتیو",
		"objective.no_objectives": "هنوز آبجکتیوی ساخته نشده است.",
		"progress.story": "پیشرفت داستان",
		"progress.quest": "پیشرفت کوئست",
		"sprint_template.start.title": "شروع",
		"sprint_template.start.subtitle": "یک اسپرینت کوتاه دو روزه برای شروع کردن بدون فشار و کمال‌گرایی.",
		"sprint_template.start.suggested_name": "اسپرینت ۰۱ - شروع",
		"sprint_template.rising.title": "برخاستن",
		"sprint_template.rising.subtitle": "یک اسپرینت متمرکز برای جمع‌وجور شدن و دوباره بلند شدن.",
		"sprint_template.rising.suggested_name": "اسپرینت ۰۱ - برخاستن",
		"sprint_template.day_zero.title": "روز صفر",
		"sprint_template.day_zero.subtitle": "یک اسپرینت بازنشانی برای خلوت کردن ذهن، مشخص کردن مسیر و آماده شدن برای شروع جدی.",
		"sprint_template.day_zero.suggested_name": "اسپرینت ۰۰ - روز صفر",
		"sprint_template.rhythm.title": "ساختن ریتم",
		"sprint_template.rhythm.subtitle": "یک اسپرینت سه روزه برای ساختن یک ریتم ساده و قابل ادامه در روزهای بعد.",
		"sprint_template.rhythm.suggested_name": "اسپرینت ۰۱ - ساختن ریتم",
		"sprint_template.focus.title": "حرکت متمرکز",
		"sprint_template.focus.subtitle": "یک اسپرینت سه روزه برای تمرکز روی یک خروجی کوچک ولی واقعی.",
		"sprint_template.focus.suggested_name": "اسپرینت ۰۱ - حرکت متمرکز",
		"template.starting_over.title": "شروع دوباره",
		"template.starting_over.description": "اگه بعد از یک تغییر سخت می‌خوای دوباره خودت رو جمع‌وجور کنی و قدم‌به‌قدم برگردی به مسیر، این قالب برای توئه. از عادت‌های ساده شروع کن، مسیرهای مهم زندگیت رو مشخص کن و کم‌کم دوباره ریتمت رو بساز.",
		"template.starting_over.goal": "دوباره یک ریتم ساده و قابل ادامه بساز.",
		"template.build_my_first_product.title": "ساخت اولین محصول",
		"template.build_my_first_product.description": "اگه یه ایده توی ذهنت داری و می‌خوای تبدیلش کنی به یک محصول کوچک و قابل استفاده، این قالب کمکت می‌کنه مرحله‌به‌مرحله جلو بری؛ از یادگیری و ساخت گرفته تا تست، بازخورد و بهتر کردن محصول.",
		"template.build_my_first_product.goal": "اولین نسخه قابل استفاده محصول را منتشر کن.",
		"template.health_reset.title": "بازسازی سلامت",
		"template.health_reset.description": "اگه حس می‌کنی انرژی، خواب، ورزش یا نظم روزانه‌ات از مسیر خارج شده، این قالب کمک می‌کنه دوباره بدنت و ذهنت رو تنظیم کنی و با قدم‌های کوچک ولی واقعی به وضعیت بهتر برسی.",
		"template.health_reset.goal": "یک روتین سالم‌تر و واقعی‌تر بساز.",
		"template.learning_sprint.title": "اسپرینت یادگیری",
		"template.learning_sprint.description": "اگه می‌خوای یک مهارت جدید رو جدی یاد بگیری، این قالب برای اینه که فقط دوره نبینی و رهاش نکنی. یاد می‌گیری، تمرین می‌کنی، پروژه می‌سازی و پیشرفتت رو قابل اندازه‌گیری می‌کنی.",
		"template.learning_sprint.goal": "یک پروژه کوچک برای مهارت جدیدت کامل کن.",
		"template.career_comeback.title": "بازگشت شغلی",
		"template.career_comeback.description": "اگه می‌خوای دوباره با قدرت وارد مسیر کاری بشی، این قالب کمکت می‌کنه رزومه‌ات رو بهتر کنی، برای فرصت‌های مناسب اقدام کنی، برای مصاحبه آماده بشی و قدم‌به‌قدم momentum حرفه‌ای بسازی.",
		"template.career_comeback.goal": "به یک فرصت کاری روشن و جدی برسی.",
		"path.health_fitness": "ورزش و سلامتی",
		"path.learning": "یادگیری",
		"path.income": "درآمد",
		"path.family": "خانواده",
		"path.creation": "ساختن و خلق کردن",
		"path.rest": "استراحت",
		"path.product": "محصول",
		"path.marketing": "بازاریابی",
		"path.nutrition": "تغذیه",
		"path.sleep": "خواب",
		"path.mindset": "ذهنیت",
		"path.study": "مطالعه",
		"path.practice": "تمرین",
		"path.projects": "پروژه‌ها",
		"path.review": "مرور",
		"path.resume": "رزومه",
		"path.applications": "ارسال درخواست",
		"path.interview_practice": "تمرین مصاحبه"
	}
}


func set_language(language: String) -> void:
	if translations.has(language):
		current_language = language


func get_language() -> String:
	return current_language


func is_rtl() -> bool:
	return current_language == PERSIAN


func text(key: String) -> String:
	if translations[current_language].has(key):
		return translations[current_language][key]

	return key
